version: '3.2'

services:
  php:
    image: geerlingguy/php-apache:5.6
    container_name: puol_php
    # restart: on-failure
    volumes:
      # - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/var/www/html:rw,delegated
    ports:
      - 15048:80
    links:
      - mariadb

  mariadb:
    image: mariadb:10.3
    container_name: puol_mariadb
    # restart: on-failure
    volumes:
      - db_persistent:/var/lib/mysql
    ports:
      - 15046:3306
    restart: always
    environment:
      - TZ=Asia/Jakarta
      - MYSQL_ROOT_PASSWORD=db_15046

volumes:
  db_persistent:
